#!/bin/bash
#PBS -N Stream2Tf
#PBS -M joshuashiing2011@gmail.com
#PBS -m abe
#PBS -A open
#PBS -l nodes=1:ppn=1
#PBS -l walltime=12:00:00
#PBS -j oe
#PBS -o ./logs

echo "Host name: `hostname`"
echo "Job Begin: `date`"

wkdir=/storage/home/gux8/work/Research/PennCNQ
cd ${wkdir}

./bin/preprocess/convert_stream_to_tfrecords.py --stream_path data/test_streams/GSOK029_7-2014.mseed --output_dir  data/EvN/test_set/GSOK029/tfrecords --window_size 10 --window_step 11 

echo "Job End: `date`"
