#!/bin/bash
#PBS -N Create_NWin
#PBS -M joshuashiing2011@gmail.com
#PBS -m abe
#PBS -A open
#PBS -l nodes=1:ppn=1
#PBS -l walltime=04:00:00
#PBS -j oe
#PBS -o ./logs

echo "Host name: `hostname`"
echo "Job Begin: `date`"

wkdir=/storage/home/gux8/work/Research/PennCNQ
cd ${wkdir}
./bin/preprocess/create_dataset_noise.py --stream_path data/streams/GSOK029_8-2014.mseed --catalog data/catalogs/Benz_catalog.csv --output_dir data/noise_OK029/noise_august

echo "Job End: `date`"
