#!/bin/bash
#PBS -N Create_EWin
#PBS -M joshuashiing2011@gmail.com
#PBS -m abe
#PBS -A open
#PBS -l nodes=1:ppn=1
#PBS -l walltime=04:00:00
#PBS -j oe
#PBS -o ./logs

echo "Host name: `hostname`"
echo "Job Begin: `date`"

wkdir=/storage/home/gux8/work/Research/PennCNQ
cd ${wkdir}
./bin/preprocess/create_dataset_events.py --stream_dir data/streams --catalog data/EvN/catalog_with_cluster_ids.csv --output_dir data/EvN/EWin --save_mseed True --plot True

echo "Job End: `date`"
