#!/bin/bash
#PBS -N Train
#PBS -M joshuashiing2011@gmail.com
#PBS -m abe
#PBS -A open
#PBS -l nodes=1:ppn=1
#PBS -l walltime=10:00:00
#PBS -j oe
#PBS -o ./logs

echo "Host name: `hostname`"
echo "Job Begin: `date`"

wkdir=/storage/home/gux8/work/Research/PennCNQ
cd ${wkdir}
./bin/train --dataset data/1_cluster/train --checkpoint_dir output/convnetquake_binary --n_clusters 1

echo "Job End: `date`"
